// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',  // optional if default location

  migrations: {
    seed: 'ts-node prisma/seed.ts',
    path: 'prisma/migrations',    // optional
  },

  datasource: {
    url: process.env.DATABASE_URL,   // or env('DATABASE_URL') if using Prisma's env helper
  },
});

